name: source_deploy

on:
  push:
    branches:
      - <span id="branch1">...</span>

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/<span id="projectnum0">...</span>/locations/global/workloadIdentityPools/example-pool/providers/example-gh-provider
          service_account: my-service-account@<span id="project7">...</span>.iam.gserviceaccount.com

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          source: .
          region: <span id="region9">...</span>
          service: <span id="service9">...</span>
